### ISSUE TITLE
Add a property to control the margin

### ISSUE THREAD

**Issue by team-moeller** [team-moeller/better-access-pivottable#22]
The margin is fixed 30px. 
It should be possible to control this value via a property

**Comment by team-moeller** [comment]
This should be the right place to change:
`<div id='output' style='margin: 30px;'></div>`

**Comment by KDGundermann** [comment]
Welche Margins meinst du?? (Finde im pivot.min.css nichts)

**Comment by team-moeller** [comment]
Die Margins stehen in der HTML-Datei. Damit habe ich dem Div mit dem Namen "output" einen Rand gegeben.
Ich habe mir das Issue jetzt zugewiesen. Ich weiß schon, wo und wie ich das anpasse.

**Comment by team-moeller** [comment]
Released with version 1.56.05
