### ISSUE TITLE
HTML file: revise MOTW

### ISSUE THREAD

**Issue by team-moeller** [team-moeller/better-access-pivottable#50]
In the generated HTML file are two comments fot the MOTW.
Only one is necessary.

**Comment by KDGundermann** [comment]
which one to keep ?
` a. <!-- saved from url=(0014)about:internet -->`
` b. <!-- saved from url=(0016)http://localhost -->`

**Comment by team-moeller** [comment]
I decided to keep line a. The text has 4 characters less. Who knows what that's good for. 😎

**Comment by team-moeller** [comment]
Released with version 1.52.01
