### ISSUE TITLE
ActiveX error. 

### ISSUE THREAD

**Issue by jimmyVadako** [team-moeller/better-access-pivottable#66]
![image](https://github.com/team-moeller/better-access-pivottable/assets/35382979/72947216-ac73-4763-b276-7d8d3999b3e6)

Also you don't have these controls or object in your form
![image](https://github.com/team-moeller/better-access-pivottable/assets/35382979/5da92dbf-d208-4327-b99e-b23e365788f7)

**Comment by team-moeller** [comment]
Hi @jimmyVadako !
Since version 2.00.11 Better Access PivotTable needs the new Edge Browser Control. This is only available in Access 365.
If you don't have Access 365 you can use version 1.65.01 at max.
